### ISSUE TITLE
Running modified services

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/stack-eda-services#12]
I found that the instructions [here](https://github.com/VEuPathDB/stack-eda-services/blob/main/README.md#2a-optional-build-images) _nearly_ worked for building a local `../EdaDataService`:

I had to comment out the `image:` line from the `data` section in `docker-compose.yml` 

```
  data:
    # image: veupathdb/eda-data:${DATA_TAG:-latest}
    networks:
      internal:
        aliases:
          - data-internal
```

Then 
```
docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-build/docker-compose-build-data.yml up
```
worked fine.
